/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.SeminarController;
import dao.Seminar;
import java.awt.print.PrinterException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author barokah
 */
public class formSeminar extends javax.swing.JPanel {

    /**
     * Creates new form formSeminar
     */
    public formSeminar() {
        initComponents();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) txtTanggalSeminarKP.getDateEditor();
        editor.setEditable(false);
        tableSeminarKP.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
//////////////////////////////////////////Tambahan//////////////////////////////////////////
    private Seminar seminar;
    private SeminarController ctrl;
    private String id;
    private String nama;
    private String perusahaan;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

    public void setController(SeminarController ctrl) {
        this.ctrl = ctrl;
    }

    public void setTableModel(AbstractTableModel tblModel) {
        tableSeminarKP.setModel(tblModel);
        final TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tableSeminarKP.getModel());
        tableSeminarKP.setRowSorter(rowSorter);
        tfCari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = tfCari.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = tfCari.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    private void clear() {
        txtNIM1SeminarKP.setText("");
        txtNIM2SeminarKP.setText("");
        txtJudulSeminarKP.setText("");
        lblID1.setText("");
        lblID2.setText("");
        txtTanggalSeminarKP.setDate(null);
        txtNIM1SeminarKP.setEnabled(true);
        txtNIM1SeminarKP.setEditable(true);
        txtNIM2SeminarKP.setEnabled(true);
        txtNIM2SeminarKP.setEditable(true);
        btnTambahSeminarKP.setEnabled(true);
        btnHapusSeminarKP.setEnabled(false);
        btnUbahSeminarKP.setEnabled(false);
        tableSeminarKP.clearSelection();
    }
//////////////////////////////////////////////////////////////////////////////////////////// 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSeminarKP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        btnTambahSeminarKP = new javax.swing.JButton();
        btnUbahSeminarKP = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        btnHapusSeminarKP = new javax.swing.JButton();
        txtNIM1SeminarKP = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtNIM2SeminarKP = new javax.swing.JTextField();
        txtTanggalSeminarKP = new com.toedter.calendar.JDateChooser();
        btnClear = new javax.swing.JButton();
        txtJudulSeminarKP = new javax.swing.JTextField();
        lblID1 = new javax.swing.JLabel();
        lblID2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(866, 440));

        jPanel8.setBackground(new java.awt.Color(28, 56, 108));
        jPanel8.setPreferredSize(new java.awt.Dimension(434, 39));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText(":: DATA SEMINAR KP ::");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel8.add(jLabel34, java.awt.BorderLayout.CENTER);

        tableSeminarKP.setAutoCreateRowSorter(true);
        tableSeminarKP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Mahasiswa", "Nama Perusahaan", "Judul Seminar", "Tanggal Seminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSeminarKP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSeminarKPMouseClicked(evt);
            }
        });
        tableSeminarKP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableSeminarKPKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tableSeminarKP);

        jLabel37.setText("Tanggal");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTambahSeminarKP.setText("Tambah");
        btnTambahSeminarKP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahSeminarKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSeminarKPActionPerformed(evt);
            }
        });

        btnUbahSeminarKP.setText("Ubah");
        btnUbahSeminarKP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahSeminarKP.setEnabled(false);
        btnUbahSeminarKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahSeminarKPActionPerformed(evt);
            }
        });

        jLabel35.setText("NIM");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnHapusSeminarKP.setText("Hapus");
        btnHapusSeminarKP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusSeminarKP.setEnabled(false);
        btnHapusSeminarKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusSeminarKPActionPerformed(evt);
            }
        });

        jLabel36.setText("Judul");
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblID1.setText(" ");

        lblID2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblID2.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblID2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTanggalSeminarKP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJudulSeminarKP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txtNIM2SeminarKP)
                            .addComponent(txtNIM1SeminarKP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnTambahSeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnUbahSeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnHapusSeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(lblID2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIM1SeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNIM2SeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudulSeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(txtTanggalSeminarKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(172, 172, 172)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambahSeminarKP)
                        .addComponent(btnUbahSeminarKP)
                        .addComponent(btnHapusSeminarKP)
                        .addComponent(btnClear))
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setText("Cari :");

        jButton1.setText("Cetak Tabel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahSeminarKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSeminarKPActionPerformed
        if (txtJudulSeminarKP.getText().isEmpty() && (txtNIM1SeminarKP.getText().isEmpty() && txtNIM2SeminarKP.getText().isEmpty()) && txtTanggalSeminarKP.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Data Tidak boleh kosong");
        } else if (txtJudulSeminarKP.getText().isEmpty() && (txtNIM1SeminarKP.getText().isEmpty() && txtNIM2SeminarKP.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "NIM dan Judul Seminar tidak boleh kosong");
        } else if (txtTanggalSeminarKP.getDate() == null && (txtNIM1SeminarKP.getText().isEmpty() && txtNIM2SeminarKP.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "NIM dan Tanggal Seminar tidak boleh kosong");
        } else if (txtJudulSeminarKP.getText().isEmpty() && txtTanggalSeminarKP.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Judul dan Tanggal Seminar tidak boleh kosong");
        } else if (txtNIM1SeminarKP.getText().isEmpty() && txtNIM2SeminarKP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIM tidak boleh kosong");
        } else if (txtJudulSeminarKP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Judul Seminar tidak boleh kosong");
        } else if (txtTanggalSeminarKP.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal Seminar tidak boleh kosong");
        } else {
            ctrl.addSeminar(txtNIM1SeminarKP.getText(), txtNIM2SeminarKP.getText(), txtJudulSeminarKP.getText(), String.valueOf(format.format(txtTanggalSeminarKP.getDate())));
            ctrl.resetTable();
            clear();
        }
    }//GEN-LAST:event_btnTambahSeminarKPActionPerformed

    private void btnUbahSeminarKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahSeminarKPActionPerformed
        seminar = new Seminar(id, nama, perusahaan, txtJudulSeminarKP.getText(), String.valueOf(format.format(txtTanggalSeminarKP.getDate())));
        ctrl.updateSeminar(seminar);
        ctrl.resetTable();
        clear();
    }//GEN-LAST:event_btnUbahSeminarKPActionPerformed

    private void btnHapusSeminarKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSeminarKPActionPerformed
        ctrl.deleteSeminar(id);
        ctrl.resetTable();
        clear();
    }//GEN-LAST:event_btnHapusSeminarKPActionPerformed

    private void tableSeminarKPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSeminarKPMouseClicked
        txtNIM1SeminarKP.setEnabled(false);
        txtNIM1SeminarKP.setEditable(false);
        txtNIM2SeminarKP.setEnabled(false);
        txtNIM2SeminarKP.setEditable(false);
        btnTambahSeminarKP.setEnabled(false);
        btnHapusSeminarKP.setEnabled(true);
        btnUbahSeminarKP.setEnabled(true);
        int row = tableSeminarKP.getSelectedRow();
        seminar = ctrl.getSeminar(row);
        id = seminar.getId();
        nama = seminar.getNama();
        perusahaan = seminar.getPerusahaan();
        txtJudulSeminarKP.setText(seminar.getJudul());
        lblID1.setText("ID Seminar");
        lblID2.setText(id);
        try {
            txtTanggalSeminarKP.setDate(format.parse(seminar.getTanggal()));
        } catch (ParseException ex) {
//            Logger.getLogger(formSeminar.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_tableSeminarKPMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tableSeminarKP.print();
        } catch (PrinterException ex) {
            //            Logger.getLogger(formDataDosen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Gagal Mencetak", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableSeminarKPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableSeminarKPKeyReleased
        txtNIM1SeminarKP.setEnabled(false);
        txtNIM1SeminarKP.setEditable(false);
        txtNIM2SeminarKP.setEnabled(false);
        txtNIM2SeminarKP.setEditable(false);
        btnTambahSeminarKP.setEnabled(false);
        btnHapusSeminarKP.setEnabled(true);
        btnUbahSeminarKP.setEnabled(true);
        int row = tableSeminarKP.getSelectedRow();
        seminar = ctrl.getSeminar(row);
        id = seminar.getId();
        nama = seminar.getNama();
        perusahaan = seminar.getPerusahaan();
        txtJudulSeminarKP.setText(seminar.getJudul());
        lblID1.setText("ID Seminar");
        lblID2.setText(id);
        try {
            txtTanggalSeminarKP.setDate(format.parse(seminar.getTanggal()));
        } catch (ParseException ex) {
//            Logger.getLogger(formSeminar.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_tableSeminarKPKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapusSeminarKP;
    private javax.swing.JButton btnTambahSeminarKP;
    private javax.swing.JButton btnUbahSeminarKP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JTable tableSeminarKP;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField txtJudulSeminarKP;
    private javax.swing.JTextField txtNIM1SeminarKP;
    private javax.swing.JTextField txtNIM2SeminarKP;
    private com.toedter.calendar.JDateChooser txtTanggalSeminarKP;
    // End of variables declaration//GEN-END:variables
}
