/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.MahasiswaController;
import dao.Mahasiswa;
import java.awt.print.PrinterException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author barokah
 */
public class formDataMhs extends javax.swing.JPanel {

    /**
     * Creates new form formDataMhs
     */
    public formDataMhs() {
        initComponents();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) txtTanggalLahirMhs.getDateEditor();
        editor.setEditable(false);
        tableMahasiswa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
//////////////////////////////////////////Tambahan//////////////////////////////////////////
    private Mahasiswa mhs;
    private MahasiswaController ctrl;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

    public void setController(MahasiswaController ctrl) {
        this.ctrl = ctrl;
    }

    public void setTableModel(AbstractTableModel tblModel) {
        tableMahasiswa.setModel(tblModel);
        final TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tableMahasiswa.getModel());
        tableMahasiswa.setRowSorter(rowSorter);
        tfCari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = tfCari.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = tfCari.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    private void clear() {
        txtNIMMhs.setText("");
        txtNamaMhs.setText("");
        txtTanggalLahirMhs.setDate(null);
        buttonGroup1.clearSelection();
        txtAsalMhs.setText("");
        txtJurusanMhs.setText("");
        txtAngkatan.setText("");
        txtNoHPMhs.setText("");
        txtNIMMhs.setEnabled(true);
        txtNIMMhs.setEditable(true);
        btnTambahMhs.setEnabled(true);
        btnHapusMhs.setEnabled(false);
        btnUbahMhs.setEnabled(false);
        tableMahasiswa.clearSelection();
    }
////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        tfCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelTengah = new javax.swing.JPanel();
        txtNIMMhs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAngkatan = new javax.swing.JTextField();
        txtTanggalLahirMhs = new com.toedter.calendar.JDateChooser();
        btnClear = new javax.swing.JButton();
        btnTambahMhs = new javax.swing.JButton();
        btnUbahMhs = new javax.swing.JButton();
        btnHapusMhs = new javax.swing.JButton();
        RB_Laki = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        RB_Perempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNoHPMhs = new javax.swing.JTextField();
        txtJurusanMhs = new javax.swing.JTextField();
        txtAsalMhs = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNamaMhs = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(866, 440));

        jPanel5.setBackground(new java.awt.Color(28, 56, 108));
        jPanel5.setPreferredSize(new java.awt.Dimension(434, 39));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(":: DATA MAHASISWA ::");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        tableMahasiswa.setAutoCreateRowSorter(true);
        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tanggal Lahir", "Jenis Kelamin", "Asal", "Jurusan", "Angkatan", "No. HP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMahasiswaMouseClicked(evt);
            }
        });
        tableMahasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableMahasiswaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableMahasiswa);

        jLabel2.setText("Cari :");

        jLabel12.setText("Asal");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setText("Angkatan");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnTambahMhs.setText("Tambah");
        btnTambahMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMhsActionPerformed(evt);
            }
        });

        btnUbahMhs.setText("Ubah");
        btnUbahMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbahMhs.setEnabled(false);
        btnUbahMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahMhsActionPerformed(evt);
            }
        });

        btnHapusMhs.setText("Hapus");
        btnHapusMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusMhs.setEnabled(false);
        btnHapusMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMhsActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_Laki);
        RB_Laki.setText("Laki - Laki");
        RB_Laki.setActionCommand("L");
        RB_Laki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("NIM");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        buttonGroup1.add(RB_Perempuan);
        RB_Perempuan.setText("Perempuan");
        RB_Perempuan.setActionCommand("P");
        RB_Perempuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setText("Nama");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setText("Tanggal Lahir");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel13.setText("Jurusan");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel14.setText("No. HP");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel11.setText("Jenis Kelamin");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout panelTengahLayout = new javax.swing.GroupLayout(panelTengah);
        panelTengah.setLayout(panelTengahLayout);
        panelTengahLayout.setHorizontalGroup(
            panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTengahLayout.createSequentialGroup()
                .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB_Perempuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RB_Laki, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNIMMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTanggalLahirMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNoHPMhs, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(txtJurusanMhs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsalMhs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAngkatan)))
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnTambahMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbahMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTengahLayout.setVerticalGroup(
            panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTengahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNIMMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTanggalLahirMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RB_Laki)
                            .addComponent(jLabel11)))
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtAsalMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtJurusanMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtNoHPMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB_Perempuan)
                .addGap(18, 18, 18)
                .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahMhs)
                    .addComponent(btnUbahMhs)
                    .addComponent(btnHapusMhs)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("Cetak Tabel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTengah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTengah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMhsActionPerformed
        if (txtNIMMhs.getText().isEmpty() && txtNamaMhs.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIM dan Nama tidak boleh kosong");
        } else if (!RB_Laki.isSelected() && !RB_Perempuan.isSelected()) {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin");
        } else if (txtNIMMhs.getText().isEmpty() || txtNamaMhs.getText().isEmpty()
                || txtTanggalLahirMhs.getDate() == null
                || txtAsalMhs.getText().isEmpty() || txtJurusanMhs.getText().isEmpty()
                || txtAngkatan.getText().isEmpty()
                || txtNoHPMhs.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Form tidak boleh ada yang kosong");
        } else {
            mhs = new Mahasiswa(
                    txtNIMMhs.getText(),
                    txtNamaMhs.getText(),
                    String.valueOf(format.format(txtTanggalLahirMhs.getDate())),
                    buttonGroup1.getSelection().getActionCommand(),
                    txtAsalMhs.getText(),
                    txtJurusanMhs.getText(),
                    txtAngkatan.getText(),
                    txtNoHPMhs.getText());
            ctrl.addMahasiswa(mhs);
            ctrl.resetTable();
            clear();
        }
    }//GEN-LAST:event_btnTambahMhsActionPerformed

    private void btnUbahMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahMhsActionPerformed
        mhs = new Mahasiswa(
                txtNIMMhs.getText(),
                txtNamaMhs.getText(),
                String.valueOf(format.format(txtTanggalLahirMhs.getDate())),
                buttonGroup1.getSelection().getActionCommand(),
                txtAsalMhs.getText(),
                txtJurusanMhs.getText(),
                txtAngkatan.getText(),
                txtNoHPMhs.getText());
        ctrl.updateMahasiswa(mhs);
        ctrl.resetTable();
        clear();
    }//GEN-LAST:event_btnUbahMhsActionPerformed

    private void btnHapusMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMhsActionPerformed
        ctrl.deleteMahasiswa(txtNIMMhs.getText());
        ctrl.resetTable();
        clear();
    }//GEN-LAST:event_btnHapusMhsActionPerformed

    private void tableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMahasiswaMouseClicked
        txtNIMMhs.setEnabled(false);
        txtNIMMhs.setEditable(false);
        btnTambahMhs.setEnabled(false);
        btnHapusMhs.setEnabled(true);
        btnUbahMhs.setEnabled(true);
        int row = tableMahasiswa.getSelectedRow();
        txtNIMMhs.setText(tableMahasiswa.getValueAt(row, 0).toString());
        txtNamaMhs.setText(tableMahasiswa.getValueAt(row, 1).toString());
        try {
            txtTanggalLahirMhs.setDate(format.parse(tableMahasiswa.getValueAt(row, 2).toString()));
        } catch (ParseException ex) {
//            Logger.getLogger(formDataMhs.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        if ("L".equals(tableMahasiswa.getValueAt(row, 3).toString())) {
            buttonGroup1.setSelected(RB_Laki.getModel(), true);
        } else {
            buttonGroup1.setSelected(RB_Perempuan.getModel(), true);
        }
        txtAsalMhs.setText(tableMahasiswa.getValueAt(row, 4).toString());
        txtJurusanMhs.setText(tableMahasiswa.getValueAt(row, 5).toString());
        txtAngkatan.setText(tableMahasiswa.getValueAt(row, 6).toString());
        txtNoHPMhs.setText(tableMahasiswa.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tableMahasiswaMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tableMahasiswa.print();
        } catch (PrinterException ex) {
            //            Logger.getLogger(formDataDosen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Gagal Mencetak", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMahasiswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableMahasiswaKeyReleased
        txtNIMMhs.setEnabled(false);
        txtNIMMhs.setEditable(false);
        btnTambahMhs.setEnabled(false);
        btnHapusMhs.setEnabled(true);
        btnUbahMhs.setEnabled(true);
        int row = tableMahasiswa.getSelectedRow();
        txtNIMMhs.setText(tableMahasiswa.getValueAt(row, 0).toString());
        txtNamaMhs.setText(tableMahasiswa.getValueAt(row, 1).toString());
        try {
            txtTanggalLahirMhs.setDate(format.parse(tableMahasiswa.getValueAt(row, 2).toString()));
        } catch (ParseException ex) {
//            Logger.getLogger(formDataMhs.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        if ("L".equals(tableMahasiswa.getValueAt(row, 3).toString())) {
            buttonGroup1.setSelected(RB_Laki.getModel(), true);
        } else {
            buttonGroup1.setSelected(RB_Perempuan.getModel(), true);
        }
        txtAsalMhs.setText(tableMahasiswa.getValueAt(row, 4).toString());
        txtJurusanMhs.setText(tableMahasiswa.getValueAt(row, 5).toString());
        txtAngkatan.setText(tableMahasiswa.getValueAt(row, 6).toString());
        txtNoHPMhs.setText(tableMahasiswa.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tableMahasiswaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RB_Laki;
    private javax.swing.JRadioButton RB_Perempuan;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapusMhs;
    private javax.swing.JButton btnTambahMhs;
    private javax.swing.JButton btnUbahMhs;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTengah;
    private javax.swing.JTable tableMahasiswa;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtAsalMhs;
    private javax.swing.JTextField txtJurusanMhs;
    private javax.swing.JTextField txtNIMMhs;
    private javax.swing.JTextField txtNamaMhs;
    private javax.swing.JTextField txtNoHPMhs;
    private com.toedter.calendar.JDateChooser txtTanggalLahirMhs;
    // End of variables declaration//GEN-END:variables
}
