/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KPController;
import dao.KP;
import java.awt.Desktop;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.xmlbeans.XmlException;

/**
 *
 * @author barokah
 */
public class formKP extends javax.swing.JPanel {

    /**
     * Creates new form formKP
     */
    public formKP() {
        initComponents();
        tableKP.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
//////////////////////////////////////////Tambahan//////////////////////////////////////////
    private KP kp;
    private KPController ctrl;

    public void setController(KPController ctrl) {
        this.ctrl = ctrl;
    }

    public void setTableModel(AbstractTableModel tblModel) {
        tableKP.setModel(tblModel);
        final TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tableKP.getModel());
        tableKP.setRowSorter(rowSorter);
        tfCari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = tfCari.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = tfCari.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    private void refresh() {
        tableKP.clearSelection();
        txtNoSurat.setText("");
        cbStatus.setSelectedIndex(0);
        txtDosenP.setText("");
        txtNoSurat.setEnabled(false);
        txtNoSurat.setEditable(false);
        txtDosenP.setEnabled(false);
        txtDosenP.setEditable(false);
        cbStatus.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnInfo.setEnabled(false);
        btnSurat.setEnabled(false);
        ctrl.resetTable();
        lblIDKP.setText("");
    }
//////////////////////////////////////////////////////////////////////////////////////////// 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNoSurat = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtDosenP = new javax.swing.JTextField();
        btnInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblIDKP = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnSurat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(866, 440));

        jPanel6.setBackground(new java.awt.Color(28, 56, 108));
        jPanel6.setPreferredSize(new java.awt.Dimension(436, 39));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText(":: DATA KERJA PRAKTEK ::");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel6.add(jLabel33, java.awt.BorderLayout.CENTER);

        tableKP.setAutoCreateRowSorter(true);
        tableKP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama Mahasiswa", "Jurusan", "Nama Perusahaan", "Tanggal Mulai", "Tanggal Selesai", "Dosen Pembimbing", "Status", "No Surat", "Tanggal Diubah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableKP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKPMouseClicked(evt);
            }
        });
        tableKP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKPKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tableKP);

        jLabel11.setText("NIP Dosen Pembimbing");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnUbah.setText("Ubah\n");
        btnUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbah.setEnabled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel13.setText("No Surat");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtNoSurat.setEditable(false);
        txtNoSurat.setEnabled(false);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terdaftar", "Diajukan", "Terkirim", "Diterima", "Kerja Praktek", "Laporan", "Selesai" }));
        cbStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbStatus.setEnabled(false);

        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel8.setText("Status");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtDosenP.setEditable(false);
        txtDosenP.setEnabled(false);

        btnInfo.setText("Info Perusahaan");
        btnInfo.setEnabled(false);
        btnInfo.setPreferredSize(new java.awt.Dimension(140, 30));
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Kerja Praktek");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblIDKP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIDKP.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDosenP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDKP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNoSurat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(84, 84, 84))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIDKP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNoSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDosenP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah))
                .addContainerGap())
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setText("Cari :");

        jPanel4.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("Cetak Tabel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSurat.setText("Buat Surat");
        btnSurat.setEnabled(false);
        btnSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(btnSurat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        KP data = ctrl.getKP(tableKP.getSelectedRow());
        data.setNip(txtDosenP.getText());
        data.setNoSurat(txtNoSurat.getText());
        data.setStatus(cbStatus.getSelectedItem().toString());
        ctrl.updateKP(data);
        refresh();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        ctrl.deleteKP(lblIDKP.getText());
        refresh();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableKPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKPMouseClicked
        txtNoSurat.setEnabled(true);
        txtNoSurat.setEditable(true);
        txtDosenP.setEnabled(true);
        txtDosenP.setEditable(true);
        cbStatus.setEnabled(true);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
        btnInfo.setEnabled(true);
        btnSurat.setEnabled(true);
        int row = tableKP.getSelectedRow();
        kp = ctrl.getKP(row);
        txtNoSurat.setText(kp.getNoSurat());
        cbStatus.setSelectedItem(kp.getStatus());
        txtDosenP.setText(kp.getNip());
        lblIDKP.setText(kp.getId());
    }//GEN-LAST:event_tableKPMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        int row = tableKP.getSelectedRow();
        kp = ctrl.getKP(row);
        String perusahaan = "<html><div style='width:300px'>"
                + "Nama   : " + kp.getNamaPerusahaan()
                + "<br><br>Alamat : " + kp.getAlamatPerusahaan()
                + "<br><br>Kontak : " + kp.getKontakPerusahaan();
        JOptionPane.showMessageDialog(this, perusahaan, "Info Perusahaan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tableKP.print();
        } catch (PrinterException ex) {
            //            Logger.getLogger(formDataDosen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Gagal Mencetak", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratActionPerformed
        Thread t = new Thread(new Runnable() {
            public void run() {
                JOptionPane.showMessageDialog(null, "Tunggu hingga dokumen terbuka");
            }
        });
        t.start();
        List<KP> lst = ctrl.getAllKP();
        String a = "";
        String b = "";
        for (KP k : lst) {
            if (k.getId().equals(lblIDKP.getText())) {
                a = a + k.getNim() + ",";
                b = b + k.getNama() + ",";
            }
        }
        String[] nim = a.split(",");
        String[] nama = b.split(",");
        int row = tableKP.getSelectedRow();
        kp = ctrl.getKP(row);
        DateFormat full = new SimpleDateFormat("d MMMM Y", new Locale("id", "ID"));
        SimpleDateFormat pendek = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        DOCX doc = new DOCX();
        try {
            Date tglmulai = pendek.parse(kp.getTanggalMulai());
            Date tglselesai = pendek.parse(kp.getTanggalSelesai());
            if (nim.length == 1) {
                doc.openFile("template/surat1.docx");
                doc.insertAtBookmark("nim1", nim[0], doc.REPLACE);
                doc.insertAtBookmark("nama1", nama[0], doc.REPLACE);
            } else if (nim.length == 2) {
                doc.openFile("template/surat2.docx");
                doc.insertAtBookmark("nim1", nim[0], doc.REPLACE);
                doc.insertAtBookmark("nama1", nama[0], doc.REPLACE);
                doc.insertAtBookmark("nim2", nim[1], doc.REPLACE);
                doc.insertAtBookmark("nama2", nama[1], doc.REPLACE);
            } else {
                doc.openFile("template/surat3.docx");
                doc.insertAtBookmark("nim1", nim[0], doc.REPLACE);
                doc.insertAtBookmark("nama1", nama[0], doc.REPLACE);
                doc.insertAtBookmark("nim2", nim[1], doc.REPLACE);
                doc.insertAtBookmark("nama2", nama[1], doc.REPLACE);
                doc.insertAtBookmark("nim3", nim[2], doc.REPLACE);
                doc.insertAtBookmark("nama3", nama[2], doc.REPLACE);
            }
            doc.insertAtBookmark("perusahaan", kp.getNamaPerusahaan(), doc.REPLACE);
            doc.insertAtBookmark("alamat", kp.getAlamatPerusahaan(), doc.REPLACE);
            doc.insertAtBookmark("jurusan1", kp.getJurusan(), doc.REPLACE);
            doc.insertAtBookmark("jurusan2", kp.getJurusan(), doc.REPLACE);
            doc.insertAtBookmark("nosurat", kp.getNoSurat(), doc.REPLACE);
            doc.insertAtBookmark("tgl", full.format(date), doc.REPLACE);
            doc.insertAtBookmark("tglmulai", full.format(tglmulai), doc.REPLACE);
            doc.insertAtBookmark("tglselesai", full.format(tglselesai), doc.REPLACE);
            doc.saveAs("temp/temp.docx");
            Desktop.getDesktop().open(new File("temp/temp.docx"));
        } catch (IOException ex) {
//            Logger.getLogger(formKP.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
        } catch (XmlException ex) {
//            Logger.getLogger(formKP.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
//            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex, "Application Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuratActionPerformed

    private void tableKPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKPKeyReleased
        txtNoSurat.setEnabled(true);
        txtNoSurat.setEditable(true);
        txtDosenP.setEnabled(true);
        txtDosenP.setEditable(true);
        cbStatus.setEnabled(true);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
        btnInfo.setEnabled(true);
        btnSurat.setEnabled(true);
        int row = tableKP.getSelectedRow();
        kp = ctrl.getKP(row);
        txtNoSurat.setText(kp.getNoSurat());
        cbStatus.setSelectedItem(kp.getStatus());
        txtDosenP.setText(kp.getNip());
        lblIDKP.setText(kp.getId());
    }//GEN-LAST:event_tableKPKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSurat;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblIDKP;
    private javax.swing.JTable tableKP;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField txtDosenP;
    private javax.swing.JTextField txtNoSurat;
    // End of variables declaration//GEN-END:variables
}
