/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author barokah
 */
public class formHome extends javax.swing.JPanel {

    /**
     * Creates new form formHome
     */
    public formHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(866, 440));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(201, 251, 254));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Selamat Datang Di Sistem Informasi Kerja Praktek");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLabel30.setPreferredSize(new java.awt.Dimension(286, 39));
        jPanel5.add(jLabel30, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.NORTH);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo ugm1.png"))); // NOI18N
        jLabel31.setText("Pilih Menu diatas Untuk Melanjutkan");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel31.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabel31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel31, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
