/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DosenController;
import controller.KPController;
import controller.MahasiswaController;
import controller.SeminarController;
import controller.SuratController;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Adhi
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    CardLayout cl;

    public Menu_Utama() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        cl = (CardLayout) (jPanel3.getLayout());
        DosenController dc = new DosenController();
        KPController kc = new KPController();
        MahasiswaController mc = new MahasiswaController();
        SeminarController sc = new SeminarController();
        SuratController scr = new SuratController();
        formHome home = new formHome();
        jPanel3.add(home, "Home");
        jPanel3.add(mc.getView(), "Data Mahasiswa");
        jPanel3.add(dc.getView(), "Data Dosen");
        jPanel3.add(kc.getView(), "Kerja Praktek");
        jPanel3.add(sc.getView(), "Seminar KP");
        jPanel3.add(scr.getView(), "Surat Tugas");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/favicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMhs = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnDosen = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnKP = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnSeminar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnSurat = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Kerja Praktek");
        setSize(new java.awt.Dimension(850, 400));

        jPanel1.setBackground(new java.awt.Color(28, 56, 108));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistem Informasi");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 251, 254));
        jLabel2.setText("Kerja Praktek");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Universitas Gadjah Mada");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jl. Yacaranda Sekip Unit IV, Yogyakarta");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo ugm2.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(28, 56, 108));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnHome.setBackground(new java.awt.Color(102, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHome.setForeground(java.awt.Color.gray);
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHomeMouseMoved(evt);
            }
        });
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 15));
        jPanel2.add(jSeparator1);

        btnMhs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMhs.setForeground(java.awt.Color.gray);
        btnMhs.setText("Data Mahasiswa");
        btnMhs.setBorder(null);
        btnMhs.setContentAreaFilled(false);
        btnMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMhs.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMhsMouseMoved(evt);
            }
        });
        btnMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMhsMouseExited(evt);
            }
        });
        btnMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMhsActionPerformed(evt);
            }
        });
        jPanel2.add(btnMhs);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 15));
        jPanel2.add(jSeparator2);

        btnDosen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDosen.setForeground(java.awt.Color.gray);
        btnDosen.setText("Data Dosen");
        btnDosen.setBorder(null);
        btnDosen.setContentAreaFilled(false);
        btnDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDosen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDosenMouseMoved(evt);
            }
        });
        btnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDosenMouseExited(evt);
            }
        });
        btnDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosenActionPerformed(evt);
            }
        });
        jPanel2.add(btnDosen);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(5, 15));
        jPanel2.add(jSeparator3);

        btnKP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKP.setForeground(java.awt.Color.gray);
        btnKP.setText("Kerja Praktek");
        btnKP.setBorder(null);
        btnKP.setContentAreaFilled(false);
        btnKP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnKPMouseMoved(evt);
            }
        });
        btnKP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKPMouseExited(evt);
            }
        });
        btnKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKPActionPerformed(evt);
            }
        });
        jPanel2.add(btnKP);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(5, 15));
        jPanel2.add(jSeparator4);

        btnSeminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSeminar.setForeground(java.awt.Color.gray);
        btnSeminar.setText("Seminar KP");
        btnSeminar.setBorder(null);
        btnSeminar.setContentAreaFilled(false);
        btnSeminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeminarMouseMoved(evt);
            }
        });
        btnSeminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeminarMouseExited(evt);
            }
        });
        btnSeminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeminar);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(5, 15));
        jPanel2.add(jSeparator5);

        btnSurat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSurat.setForeground(java.awt.Color.gray);
        btnSurat.setText("Surat Tugas");
        btnSurat.setBorder(null);
        btnSurat.setContentAreaFilled(false);
        btnSurat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSurat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSuratMouseMoved(evt);
            }
        });
        btnSurat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuratMouseExited(evt);
            }
        });
        btnSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratActionPerformed(evt);
            }
        });
        jPanel2.add(btnSurat);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setPreferredSize(new java.awt.Dimension(5, 15));
        jPanel2.add(jSeparator6);

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogout.setForeground(java.awt.Color.gray);
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLogoutMouseMoved(evt);
            }
        });
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);

        jPanel9.setBackground(new java.awt.Color(201, 251, 254));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel28.setText("Created by : Team Beyond4");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 448, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGap(33, 33, 33)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        cl.show(jPanel3, "Home");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMhsActionPerformed
        cl.show(jPanel3, "Data Mahasiswa");
    }//GEN-LAST:event_btnMhsActionPerformed

    private void btnDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosenActionPerformed
        cl.show(jPanel3, "Data Dosen");
    }//GEN-LAST:event_btnDosenActionPerformed

    private void btnKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKPActionPerformed
        cl.show(jPanel3, "Kerja Praktek");
    }//GEN-LAST:event_btnKPActionPerformed

    private void btnSeminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeminarActionPerformed
        cl.show(jPanel3, "Seminar KP");
    }//GEN-LAST:event_btnSeminarActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
        new Menu_Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseMoved
        btnHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnHomeMouseMoved

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnMhsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMhsMouseMoved
        btnMhs.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMhsMouseMoved

    private void btnMhsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMhsMouseExited
        btnMhs.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnMhsMouseExited

    private void btnDosenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosenMouseMoved
        btnDosen.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDosenMouseMoved

    private void btnDosenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosenMouseExited
        btnDosen.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnDosenMouseExited

    private void btnKPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKPMouseMoved
        btnKP.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnKPMouseMoved

    private void btnKPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKPMouseExited
        btnKP.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnKPMouseExited

    private void btnSeminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeminarMouseMoved
        btnSeminar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSeminarMouseMoved

    private void btnSeminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeminarMouseExited
        btnSeminar.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnSeminarMouseExited

    private void btnLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseMoved
        btnLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLogoutMouseMoved

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnSuratMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuratMouseMoved
        btnSurat.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSuratMouseMoved

    private void btnSuratMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuratMouseExited
        btnSurat.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnSuratMouseExited

    private void btnSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratActionPerformed
        cl.show(jPanel3, "Surat Tugas");
    }//GEN-LAST:event_btnSuratActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDosen;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKP;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMhs;
    private javax.swing.JButton btnSeminar;
    private javax.swing.JButton btnSurat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
